### ISSUE TITLE
Latest release is too old

### ISSUE THREAD

**Issue by alexole** [systemd/python-systemd#99] opened 2021-08-31 07:24 UTC
Hello,

Could you please make a new release? It's been awhile since the last one.
I am in a need of this functionality which was added quite some time ago https://github.com/systemd/python-systemd/pull/87

Thanks!

**Comment by keszybz** [comment] 2021-10-06 13:13
Yeah.

**Comment by kloczek** [comment] 2021-10-10 23:17
+1

**Comment by mbiebl** [comment] 2022-03-05 17:32
> Yeah.

Hi @keszybz, any updates here?

**Comment by mbiebl** [comment] 2022-03-05 17:32
Duplicate of  #76.
We should close one of the two.

**Closed** 2022-08-13 19:40 UTC
